Fix class leading comments order
openlayers/jsdoc-plugin-typescript pull request #58
Opened 2024-08-27 09:46 UTC by Daniel-Knights

Where class leading comments are being moved from the export node to the class node, they are looped in reverse order and pushed. If an exported class has multiple block comments before it (not just JSDoc comments), their order is reversed and the first comment block is processed as the leading comment instead of the last. 

If the first block comment isn't a JSDoc comment, the class will be excluded from the generated HTML files. If the first block comment _is_ a JSDoc comment, the class _will_ be in the generated HTML files, but documented with the first comment instead of the one immediately preceding it.

[Minimal repro](https://github.com/Daniel-Knights/jsdoc-plugin-typescript-class-leading-comments-bug).

2024-08-28 17:45 UTC, tschaub commented
Thanks for the proposed change, @Daniel-Knights.  It looks like you might have your editor set up to make syntax changes according to some style guidelines that you have configured globally (or otherwise outside of the project directory).

The project's style guidelines are configured with ESLint rules and those rules are enforced by a version of ESLint that is configured in the `project.json` file.  I added a [contributing doc](https://github.com/openlayers/jsdoc-plugin-typescript/blob/main/contributing.md) with details on getting a development environment set up, running the tests, and conforming with the linter rules.  Let us know if it would be useful to have additional detail in that doc.

Linter issues aside, it would be great if you could add a test that demonstrates what this fix is about.

2024-09-05 22:23 UTC, Daniel-Knights commented
Added a test @tschaub. To clarify, in the added test `/* Comment */` and `/** Doclet */` get swapped with `.push`, and `/* Comment */` is considered the leading comment of the class instead of `/** Doclet */`. The fix is to use `.unshift` instead to ensure they remain in the correct order.

2024-09-09 11:17 UTC, ahocevar requested changes
Looks good now. Please squash the first two commits (or all three, if that's easier for you) into one to avoid the back and forth on trailing commas.

2024-09-13 21:19 UTC, ahocevar approved these changes

2024-09-13 21:19 UTC, merged

2024-09-13 21:19 UTC, ahocevar commented
Thanks, @Daniel-Knights